SELECT * FROM
(
SELECT * ROWNUM NUM,A.* FROM
(
 SELECT * from MEMBERS order by REGDATE DESC
)A
)where num between 11 and 20;
SELECT * FROM
(SELECT ROW_NUMBER() OVER (ORDER BY REGDATE)DESC )NUM,MEMVER 
WHERE NUM BETWEEN 11 AND 20;